/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Challenges: typeof import('./src/components/Challenges.vue')['default']
    CourseSection: typeof import('./src/components/JobReadyPage/CourseSection.vue')['default']
    Diversity: typeof import('./src/components/Diversity.vue')['default']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    Footer: typeof import('./src/components/layouts/Footer.vue')['default']
    Header: typeof import('./src/components/layouts/Header.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    JobReady: typeof import('./src/components/JobReadyPage/JobReady.vue')['default']
    JobSection: typeof import('./src/components/JobReadyPage/JobSection.vue')['default']
    Quessionnaire: typeof import('./src/components/Quessionnaire.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettlementSol: typeof import('./src/components/SettlementSol.vue')['default']
    Topbtn: typeof import('./src/components/layouts/Topbtn.vue')['default']
  }
}
